<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>7 Einführung in das Datenhandling | Computational Methods in der politischen Kommunikationsforschung</title>
  <meta name="description" content="7 Einführung in das Datenhandling | Computational Methods in der politischen Kommunikationsforschung" />
  <meta name="generator" content="bookdown 0.18 and GitBook 2.6.7" />

  <meta property="og:title" content="7 Einführung in das Datenhandling | Computational Methods in der politischen Kommunikationsforschung" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="7 Einführung in das Datenhandling | Computational Methods in der politischen Kommunikationsforschung" />
  
  
  

<meta name="author" content="Julian Unkel" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="workflow.html"/>
<link rel="next" href="workingwithdata.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Methodische Vertiefung: Computational Methods</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Einführung</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#seminarinformationen"><i class="fa fa-check"></i>Seminarinformationen</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#ablauf-des-kurses"><i class="fa fa-check"></i>Ablauf des Kurses</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#motivation-und-ziele-des-seminars"><i class="fa fa-check"></i>Motivation und Ziele des Seminars</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#warum-also-eine-programmiersprache-für-datenanalyse-lernen"><i class="fa fa-check"></i>Warum also eine Programmiersprache für Datenanalyse lernen?</a></li>
<li><a href="index.html#warum-r-lernen">Warum <em>R</em> lernen?</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#hinweise-zur-nutzung-des-online-kurses"><i class="fa fa-check"></i>Hinweise zur Nutzung des Online-Kurses</a></li>
</ul></li>
<li class="part"><span><b>I Eine kurze Einführung in R</b></span></li>
<li class="chapter" data-level="1" data-path="firststeps.html"><a href="firststeps.html"><i class="fa fa-check"></i><b>1</b> Installation und erste Schritte</a><ul>
<li class="chapter" data-level="1.1" data-path="firststeps.html"><a href="firststeps.html#rinstallieren"><i class="fa fa-check"></i><b>1.1</b> R installieren</a></li>
<li class="chapter" data-level="1.2" data-path="firststeps.html"><a href="firststeps.html#rstudioinstallieren"><i class="fa fa-check"></i><b>1.2</b> RStudio installieren</a></li>
<li class="chapter" data-level="1.3" data-path="firststeps.html"><a href="firststeps.html#oberflaeche"><i class="fa fa-check"></i><b>1.3</b> Die Benutzeroberfläche von RStudio</a><ul>
<li class="chapter" data-level="1.3.1" data-path="firststeps.html"><a href="firststeps.html#konsole"><i class="fa fa-check"></i><b>1.3.1</b> Konsole</a></li>
<li class="chapter" data-level="1.3.2" data-path="firststeps.html"><a href="firststeps.html#r-skripte"><i class="fa fa-check"></i><b>1.3.2</b> R-Skripte</a></li>
<li class="chapter" data-level="1.3.3" data-path="firststeps.html"><a href="firststeps.html#environment"><i class="fa fa-check"></i><b>1.3.3</b> Environment</a></li>
<li class="chapter" data-level="1.3.4" data-path="firststeps.html"><a href="firststeps.html#files"><i class="fa fa-check"></i><b>1.3.4</b> Files</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="firststeps.html"><a href="firststeps.html#anpassen"><i class="fa fa-check"></i><b>1.4</b> RStudio anpassen</a></li>
<li class="chapter" data-level="1.5" data-path="firststeps.html"><a href="firststeps.html#übungsaufgaben"><i class="fa fa-check"></i><b>1.5</b> Übungsaufgaben</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html"><i class="fa fa-check"></i><b>2</b> Objekte und Datenstrukturen</a><ul>
<li class="chapter" data-level="2.1" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#objektnamen"><i class="fa fa-check"></i><b>2.1</b> Objektnamen</a></li>
<li class="chapter" data-level="2.2" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#objekttypen"><i class="fa fa-check"></i><b>2.2</b> Objekttypen</a><ul>
<li class="chapter" data-level="2.2.1" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#numerische-objekte"><i class="fa fa-check"></i><b>2.2.1</b> Numerische Objekte</a></li>
<li class="chapter" data-level="2.2.2" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#textobjekte"><i class="fa fa-check"></i><b>2.2.2</b> Textobjekte</a></li>
<li class="chapter" data-level="2.2.3" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#logicals"><i class="fa fa-check"></i><b>2.2.3</b> Logicals (logische Objekte)</a></li>
<li class="chapter" data-level="2.2.4" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#weitere-objekttypen"><i class="fa fa-check"></i><b>2.2.4</b> Weitere Objekttypen</a></li>
<li class="chapter" data-level="2.2.5" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#missingvals"><i class="fa fa-check"></i><b>2.2.5</b> Fehlende Werte</a></li>
<li class="chapter" data-level="2.2.6" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#coercion"><i class="fa fa-check"></i><b>2.2.6</b> Objekttypen ändern</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#datenstrukturen"><i class="fa fa-check"></i><b>2.3</b> Datenstrukturen</a><ul>
<li class="chapter" data-level="2.3.1" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#vectors"><i class="fa fa-check"></i><b>2.3.1</b> Vektoren</a></li>
<li class="chapter" data-level="2.3.2" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#listen"><i class="fa fa-check"></i><b>2.3.2</b> Listen</a></li>
<li class="chapter" data-level="2.3.3" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#matrizen"><i class="fa fa-check"></i><b>2.3.3</b> Matrizen</a></li>
<li class="chapter" data-level="2.3.4" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#dataframes"><i class="fa fa-check"></i><b>2.3.4</b> Dataframes</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="objekte-und-datenstrukturen.html"><a href="objekte-und-datenstrukturen.html#übungsaufgaben-1"><i class="fa fa-check"></i><b>2.4</b> Übungsaufgaben</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="funktionen.html"><a href="funktionen.html"><i class="fa fa-check"></i><b>3</b> Funktionen</a><ul>
<li class="chapter" data-level="3.1" data-path="funktionen.html"><a href="funktionen.html#funktionen-aufrufen"><i class="fa fa-check"></i><b>3.1</b> Funktionen aufrufen</a><ul>
<li class="chapter" data-level="3.1.1" data-path="funktionen.html"><a href="funktionen.html#funktionsargumente"><i class="fa fa-check"></i><b>3.1.1</b> Funktionsargumente</a></li>
<li class="chapter" data-level="3.1.2" data-path="funktionen.html"><a href="funktionen.html#hilfestellungen-zu-funktionen"><i class="fa fa-check"></i><b>3.1.2</b> Hilfestellungen zu Funktionen</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="funktionen.html"><a href="funktionen.html#eigene-funktionen-erstellen"><i class="fa fa-check"></i><b>3.2</b> Eigene Funktionen erstellen</a><ul>
<li class="chapter" data-level="3.2.1" data-path="funktionen.html"><a href="funktionen.html#funktionen-erstellen-wann-und-warum"><i class="fa fa-check"></i><b>3.2.1</b> Funktionen erstellen: wann und warum?</a></li>
<li class="chapter" data-level="3.2.2" data-path="funktionen.html"><a href="funktionen.html#aufbau-und-erstellung-von-funktionen"><i class="fa fa-check"></i><b>3.2.2</b> Aufbau und Erstellung von Funktionen</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="funktionen.html"><a href="funktionen.html#übungsaufgaben-2"><i class="fa fa-check"></i><b>3.3</b> Übungsaufgaben</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html"><i class="fa fa-check"></i><b>4</b> Kontrollstrukturen</a><ul>
<li class="chapter" data-level="4.1" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#conditions"><i class="fa fa-check"></i><b>4.1</b> Bedingungen</a><ul>
<li class="chapter" data-level="4.1.1" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#if-bedingungen"><i class="fa fa-check"></i><b>4.1.1</b> <code>if</code>-Bedingungen</a></li>
<li class="chapter" data-level="4.1.2" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#if-else-bedingungen"><i class="fa fa-check"></i><b>4.1.2</b> <code>if</code>-<code>else</code>-Bedingungen</a></li>
<li class="chapter" data-level="4.1.3" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#bedingungen-verketten"><i class="fa fa-check"></i><b>4.1.3</b> Bedingungen verketten</a></li>
<li class="chapter" data-level="4.1.4" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#mehrere-bedingungen"><i class="fa fa-check"></i><b>4.1.4</b> Mehrere Bedingungen</a></li>
<li class="chapter" data-level="4.1.5" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#mehrere-prüfwerte"><i class="fa fa-check"></i><b>4.1.5</b> Mehrere Prüfwerte</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#iterationen"><i class="fa fa-check"></i><b>4.2</b> Iterationen</a><ul>
<li class="chapter" data-level="4.2.1" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#vektorisierte-funktionen"><i class="fa fa-check"></i><b>4.2.1</b> Vektorisierte Funktionen</a></li>
<li class="chapter" data-level="4.2.2" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#forloops"><i class="fa fa-check"></i><b>4.2.2</b> <code>for</code>-Loops</a></li>
<li class="chapter" data-level="4.2.3" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#while-loops"><i class="fa fa-check"></i><b>4.2.3</b> <code>while</code>-Loops</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="kontrollstrukturen.html"><a href="kontrollstrukturen.html#übungsaufgaben-3"><i class="fa fa-check"></i><b>4.3</b> Übungsaufgaben</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="packages.html"><a href="packages.html"><i class="fa fa-check"></i><b>5</b> Packages</a><ul>
<li class="chapter" data-level="5.1" data-path="packages.html"><a href="packages.html#packages-installieren"><i class="fa fa-check"></i><b>5.1</b> Packages installieren</a></li>
<li class="chapter" data-level="5.2" data-path="packages.html"><a href="packages.html#usepackages"><i class="fa fa-check"></i><b>5.2</b> Packages nutzen</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="workflow.html"><a href="workflow.html"><i class="fa fa-check"></i><b>6</b> Workflow</a><ul>
<li class="chapter" data-level="6.1" data-path="workflow.html"><a href="workflow.html#arbeitsverzeichnisse"><i class="fa fa-check"></i><b>6.1</b> Arbeitsverzeichnisse</a></li>
<li class="chapter" data-level="6.2" data-path="workflow.html"><a href="workflow.html#rprojects"><i class="fa fa-check"></i><b>6.2</b> Projekte und Ordnerstrukturen</a></li>
<li class="chapter" data-level="6.3" data-path="workflow.html"><a href="workflow.html#r-markdown"><i class="fa fa-check"></i><b>6.3</b> R Markdown</a><ul>
<li class="chapter" data-level="6.3.1" data-path="workflow.html"><a href="workflow.html#yaml-header"><i class="fa fa-check"></i><b>6.3.1</b> YAML-Header</a></li>
<li class="chapter" data-level="6.3.2" data-path="workflow.html"><a href="workflow.html#freitext-in-markdown"><i class="fa fa-check"></i><b>6.3.2</b> Freitext in Markdown</a></li>
<li class="chapter" data-level="6.3.3" data-path="workflow.html"><a href="workflow.html#code-chunks"><i class="fa fa-check"></i><b>6.3.3</b> Code Chunks</a></li>
<li class="chapter" data-level="6.3.4" data-path="workflow.html"><a href="workflow.html#ausgabedateien-erzeugen"><i class="fa fa-check"></i><b>6.3.4</b> Ausgabedateien erzeugen</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="workflow.html"><a href="workflow.html#r-aktuell-halten"><i class="fa fa-check"></i><b>6.4</b> R aktuell halten</a><ul>
<li class="chapter" data-level="6.4.1" data-path="workflow.html"><a href="workflow.html#packages-aktualisieren"><i class="fa fa-check"></i><b>6.4.1</b> Packages aktualisieren</a></li>
<li class="chapter" data-level="6.4.2" data-path="workflow.html"><a href="workflow.html#rstudio-aktualisieren"><i class="fa fa-check"></i><b>6.4.2</b> RStudio aktualisieren</a></li>
<li class="chapter" data-level="6.4.3" data-path="workflow.html"><a href="workflow.html#r-aktualisieren"><i class="fa fa-check"></i><b>6.4.3</b> R aktualisieren</a></li>
</ul></li>
</ul></li>
<li class="part"><span><b>II Datenhandling in R</b></span></li>
<li class="chapter" data-level="7" data-path="einführung-in-das-datenhandling.html"><a href="einführung-in-das-datenhandling.html"><i class="fa fa-check"></i><b>7</b> Einführung in das Datenhandling</a><ul>
<li class="chapter" data-level="7.1" data-path="einführung-in-das-datenhandling.html"><a href="einführung-in-das-datenhandling.html#daten--und-dateiformate-tabellarischer-daten"><i class="fa fa-check"></i><b>7.1</b> Daten- und Dateiformate tabellarischer Daten</a><ul>
<li class="chapter" data-level="7.1.1" data-path="einführung-in-das-datenhandling.html"><a href="einführung-in-das-datenhandling.html#tidy-data"><i class="fa fa-check"></i><b>7.1.1</b> Tidy data</a></li>
<li class="chapter" data-level="7.1.2" data-path="einführung-in-das-datenhandling.html"><a href="einführung-in-das-datenhandling.html#dateiformate"><i class="fa fa-check"></i><b>7.1.2</b> Dateiformate</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="einführung-in-das-datenhandling.html"><a href="einführung-in-das-datenhandling.html#willkommen-im-tidyverse"><i class="fa fa-check"></i><b>7.2</b> Willkommen im Tidyverse</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="workingwithdata.html"><a href="workingwithdata.html"><i class="fa fa-check"></i><b>8</b> Daten laden, modifizieren und speichern</a><ul>
<li class="chapter" data-level="8.1" data-path="workingwithdata.html"><a href="workingwithdata.html#daten-laden"><i class="fa fa-check"></i><b>8.1</b> Daten laden</a><ul>
<li class="chapter" data-level="8.1.1" data-path="workingwithdata.html"><a href="workingwithdata.html#csv-dateien-einlesen"><i class="fa fa-check"></i><b>8.1.1</b> CSV-Dateien einlesen</a></li>
<li class="chapter" data-level="8.1.2" data-path="workingwithdata.html"><a href="workingwithdata.html#andere-dateiformate"><i class="fa fa-check"></i><b>8.1.2</b> Andere Dateiformate</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="workingwithdata.html"><a href="workingwithdata.html#daten-modifizieren"><i class="fa fa-check"></i><b>8.2</b> Daten modifizieren</a><ul>
<li class="chapter" data-level="8.2.1" data-path="workingwithdata.html"><a href="workingwithdata.html#variablen-spaltenweise-auswählen-mit-select"><i class="fa fa-check"></i><b>8.2.1</b> Variablen spaltenweise auswählen mit <code>select()</code></a></li>
<li class="chapter" data-level="8.2.2" data-path="workingwithdata.html"><a href="workingwithdata.html#variablen-zeilenweise-filtern-mit-filter"><i class="fa fa-check"></i><b>8.2.2</b> Variablen zeilenweise filtern mit <code>filter()</code></a></li>
<li class="chapter" data-level="8.2.3" data-path="workingwithdata.html"><a href="workingwithdata.html#daten-sortieren-mit-arrange"><i class="fa fa-check"></i><b>8.2.3</b> Daten sortieren mit <code>arrange()</code></a></li>
<li class="chapter" data-level="8.2.4" data-path="workingwithdata.html"><a href="workingwithdata.html#neue-variablen-hinzufügen-mit-mutate"><i class="fa fa-check"></i><b>8.2.4</b> Neue Variablen hinzufügen mit <code>mutate()</code></a></li>
<li class="chapter" data-level="8.2.5" data-path="workingwithdata.html"><a href="workingwithdata.html#variablen-zusammenfassen-mit-summarize"><i class="fa fa-check"></i><b>8.2.5</b> Variablen zusammenfassen mit <code>summarize()</code></a></li>
<li class="chapter" data-level="8.2.6" data-path="workingwithdata.html"><a href="workingwithdata.html#variablen-gruppieren-mit-group_by"><i class="fa fa-check"></i><b>8.2.6</b> Variablen gruppieren mit <code>group_by()</code></a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="workingwithdata.html"><a href="workingwithdata.html#daten-speichern"><i class="fa fa-check"></i><b>8.3</b> Daten speichern</a><ul>
<li class="chapter" data-level="8.3.1" data-path="workingwithdata.html"><a href="workingwithdata.html#tabellarische-daten-exportieren"><i class="fa fa-check"></i><b>8.3.1</b> Tabellarische Daten exportieren</a></li>
<li class="chapter" data-level="8.3.2" data-path="workingwithdata.html"><a href="workingwithdata.html#r-objekte-exportieren"><i class="fa fa-check"></i><b>8.3.2</b> R-Objekte exportieren</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="workingwithdata.html"><a href="workingwithdata.html#übungsaufgaben-4"><i class="fa fa-check"></i><b>8.4</b> Übungsaufgaben</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="der-pipe-operator.html"><a href="der-pipe-operator.html"><i class="fa fa-check"></i><b>9</b> Der Pipe-Operator <code>%&gt;%</code></a><ul>
<li class="chapter" data-level="9.1" data-path="der-pipe-operator.html"><a href="der-pipe-operator.html#lesbarkeit-verschachtelter-funktionen"><i class="fa fa-check"></i><b>9.1</b> Lesbarkeit verschachtelter Funktionen</a></li>
<li class="chapter" data-level="9.2" data-path="der-pipe-operator.html"><a href="der-pipe-operator.html#ein-beispiel-in-pseudo-code"><i class="fa fa-check"></i><b>9.2</b> Ein Beispiel in Pseudo-Code</a></li>
<li class="chapter" data-level="9.3" data-path="der-pipe-operator.html"><a href="der-pipe-operator.html#formale-definition"><i class="fa fa-check"></i><b>9.3</b> Formale Definition</a></li>
<li class="chapter" data-level="9.4" data-path="der-pipe-operator.html"><a href="der-pipe-operator.html#einsatz-von-pipes-im-tidyverse"><i class="fa fa-check"></i><b>9.4</b> Einsatz von Pipes im Tidyverse</a></li>
<li class="chapter" data-level="9.5" data-path="der-pipe-operator.html"><a href="der-pipe-operator.html#übungsaufgaben-5"><i class="fa fa-check"></i><b>9.5</b> Übungsaufgaben</a></li>
</ul></li>
<li class="appendix"><span><b>Anhang</b></span></li>
<li class="chapter" data-level="A" data-path="loesungen.html"><a href="loesungen.html"><i class="fa fa-check"></i><b>A</b> Lösungen der Übungsaufgaben</a><ul>
<li class="chapter" data-level="" data-path="loesungen.html"><a href="loesungen.html#kapitel-2-objekte-und-datenstrukturen"><i class="fa fa-check"></i>Kapitel 2: Objekte und Datenstrukturen</a></li>
<li class="chapter" data-level="" data-path="loesungen.html"><a href="loesungen.html#kapitel-3-funktionen"><i class="fa fa-check"></i>Kapitel 3: Funktionen</a></li>
<li class="chapter" data-level="" data-path="loesungen.html"><a href="loesungen.html#kapitel-4-kontrollstrukturen"><i class="fa fa-check"></i>Kapitel 4: Kontrollstrukturen</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Computational Methods in der politischen Kommunikationsforschung</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="einführung-in-das-datenhandling" class="section level1">
<h1><span class="header-section-number">7</span> Einführung in das Datenhandling</h1>
<p>Das <a href="https://de.wikipedia.org/wiki/Paretoprinzip">Paretoprinzip</a> – 80% der Ergebnisse werden mit 20% des Aufwands, 20% der Ergebnisse mit 80% des Aufwands erreicht – behält auch im datenanalytischen Kontext seine Gültigkeit: einen Großteil der Arbeitszeit wird darauf verwendet, Daten zu finden, zu importieren, zu säubern, zu transformieren, zu modifizieren und zu explorieren; die tatsächliche Analyse der Daten hingegen ist dann verhältnismäßig schnell erledigt. Wir fassen diese Schritte unter dem Begriff des <em>Datenhandlings</em> zusammen.</p>
<div id="daten--und-dateiformate-tabellarischer-daten" class="section level2">
<h2><span class="header-section-number">7.1</span> Daten- und Dateiformate tabellarischer Daten</h2>
<p>Wenn wir von Datensätzen sprechen, denken wir zumeist direkt an tabellarische Daten. In den kommenden Kapiteln werden wir auch zunächst lediglich mit tabellarischen Daten arbeiten. Daten können und werden aber auch in anderen Datenformaten repräsentiert, zum Beispiel als verschachtelte und hierarchisch strukturierte Daten (dieses Datenformat wird uns u.a. bei der Arbeit mit APIs begegnen) oder als unstrukturierte Textdokumente – dazu an gegegeber Stelle mehr.</p>
<div id="tidy-data" class="section level3">
<h3><span class="header-section-number">7.1.1</span> Tidy data</h3>
<p>Dieselben Daten können in Tabellen unterschiedlich repräsentiert werden. Schauen wir uns dazu einen Datensatz an – was könnten hier Probleme sein?</p>
<pre><code>## # A tibble: 8 x 3
##   name             variable value
##   &lt;chr&gt;            &lt;chr&gt;    &lt;dbl&gt;
## 1 Anakin Skywalker height     188
## 2 Anakin Skywalker mass        84
## 3 Leia Organa      height     150
## 4 Leia Organa      mass        49
## 5 Luke Skywalker   height     172
## 6 Luke Skywalker   mass        77
## 7 Obi-Wan Kenobi   height     182
## 8 Obi-Wan Kenobi   mass        77</code></pre>
<p>Diese Datenanordnung ist in dreierlei Hinsicht nicht optimal, wobei alle Probleme miteinander verbunden sind:</p>
<ol style="list-style-type: decimal">
<li>Zwei Variablen sind in einer Spalte hinterlegt: <code>value</code> enthält sowohl Werte, die sich auf die Körpergröße als auch auf das Gewicht beziehen.</li>
<li>Entsprechend ist die Spalte <code>value</code> abhängig von der Spalte <code>variable</code> – allein anhand der Werte <code>188</code>, <code>84</code>, <code>150</code> etc. wissen wir nicht, ob diese sich auf die Größe <code>height</code> oder das Gewicht <code>mass</code> beziehen.</li>
<li>Daraus folgt, dass wir Probleme mit vektorisierten Funktionen – wir erinnern uns, in R sind Spalten in Datensätzen Vektoren – bekommen: wir können beispielsweise nicht einfach die <code>mean()</code>-Funktion auf die Spalte <code>value</code> anwenden, um das Durchschnittsgewicht der Star-Wars-Charaktere zu berechnen, da dort auch die Werte für die Körpergröße enthalten wären.</li>
</ol>
<p>Schauen wir uns eine zweite Version derselben Daten an:</p>
<pre><code>## # A tibble: 4 x 2
##   name             height_and_mass
##   &lt;chr&gt;            &lt;chr&gt;          
## 1 Anakin Skywalker 188;84         
## 2 Leia Organa      150;49         
## 3 Luke Skywalker   172;77         
## 4 Obi-Wan Kenobi   182;77</code></pre>
<p>Auch hier ergeben sich zwei miteinander verbundene Probleme:</p>
<ol style="list-style-type: decimal">
<li>In einer Zelle stehen zwei Werte, die je eine unterschiedliche Variable abbilden.</li>
<li>Sowohl bei Körpergröße als auch Gewicht handelt es sich um numerische Werte, sie werden aber hier als <code>character</code> gespeichert, wodurch wir keine Berechnungen durchführen können.</li>
</ol>
<p>Dieselben Daten können wir jedoch auch besser tabellarisch abbilden:</p>
<pre><code>## # A tibble: 4 x 3
##   name             height  mass
##   &lt;chr&gt;             &lt;int&gt; &lt;dbl&gt;
## 1 Anakin Skywalker    188    84
## 2 Leia Organa         150    49
## 3 Luke Skywalker      172    77
## 4 Obi-Wan Kenobi      182    77</code></pre>
<p>Daten, die so aufbereitet, werden als <em>tidy data</em> bezeichnet. Sie befolgen drei Regeln:</p>
<ul>
<li>Jede Variable steht in einer eigenen Spalte</li>
<li>Jede Beobachtung/jeder Fall steht in einer eigenen Zeile</li>
<li>Jeder Wert steht in einer Zelle</li>
</ul>
<div class="figure">
<img src="img/7/tidy.png" alt="Tidy data (Quelle: R for Data Science)" />
<p class="caption">Tidy data (Quelle: <a href="https://r4ds.had.co.nz/tidy-data.html">R for Data Science</a>)</p>
</div>
<p>Im Umkehrschluss bedeutet dies, dass Daten die nicht diesen Regeln folgen, als <em>messy data</em> vorliegen und entsprechend aufbereitet werden sollten. Tidy data hat zwei entscheidende Vorteile:</p>
<ol style="list-style-type: decimal">
<li>Konsistent aufbereitete Daten sind leichter zu lesen, zu verarbeiten, zu laden und zu speichern.</li>
<li>Viele Verfahren (bzw. die zugehörigen Funktionen) in R setzen diese Art der Daten voraus.</li>
</ol>
<p>Wenn Sie bisher vor allem mit Daten aus Befragungssoftware o.ä. gearbeitet haben, dann werden Ihnen diese Grundprinzipien bereits vertraut sein, da der Datenexport aus Befragungssoftware in der Regel diesen Prinzipien folgt. Tatsächlich liegen in der “Realität” Daten aber häufig nicht in dieser Form vor, beispielsweise weil die Eingabe oder Speicherung der Daten anderen Prinzipien als einer möglichst einfachen Analyse folgt (z. B. möglichst einfache Dateneingabe; Abruf von bestimmten Werten).</p>
</div>
<div id="dateiformate" class="section level3">
<h3><span class="header-section-number">7.1.2</span> Dateiformate</h3>
<p>Sie kennen vermutlich bereits eine Vielzahl an Dateiformaten, in denen tabellarische Daten gespeichert werden können. Einige Beispiel sind Excel-Dateien mit den Endungen <code>.xls</code> bzw. <code>.xlsx</code> oder SPSS-Dateien mit der Endung <code>.sav</code>. Hierbei handelt es sich um sogenannte <em>proprietäre</em> Dateiformate, sich im Eigentum von Unternehmen befindlichen und oft softwarespezifischen Dateiformaten. Ein Vorteil dieser Formate ist es, dass oft relevante Zusatzinformationen für die jeweilige Software mitgespeichert wird, etwa Formatierungen in Excel oder Wertebeschriftungen in SPSS. Zugleich entsteht hierbei der große Nachteil, dass der Austausch der Daten zwischen verschiedenen Programmen oft recht kompliziert, durch Zusatzpakete oder Zwischenschritte möglich ist.</p>
<p>Ein <em>offenes</em> und sehr simples Dateiformat ist <code>.csv</code> (für <em>c</em>omma-<em>s</em>eparated <em>v</em>alues), das tabellarische Daten als Klartext abspeichert, von so gut wie jedem Programm auf jedem Computer der Welt gelesen werden kann und daher das Standardformat für tabellarische Daten ist. Dabei werden Kommas zu Trennung von Spalten und Zeilenumbrüche zur Trennung von Zeilen genutzt, wobei in der ersten Zeile optional Spaltenüberschriften stehen können. Die Daten aus obigen Beispiel sähen als <code>.csv</code> also so aus:</p>
<pre><code>name,height,mass
Anakin Skywalker,188,84
Leia Organa,150,49
Luke Skywalker,172,77
Obi-Wan Kenobi,182,77</code></pre>
<p>Soll das Trennzeichen in den einzelnen Text-Werten vorkommen (beispielsweise als Komma in einem Satz), werden Textbegrenzungszeichen, häufig doppelte Anführungszeichen <code>"</code> verwendet:</p>
<pre><code>name,height,mass
&quot;Skywalker, Anakin&quot;,188,84
&quot;Organa, Leia&quot;,150,49
&quot;Skywalker, Luke&quot;,172,77
&quot;Kenobi, Obi-Wan&quot;,182,77</code></pre>
<p>In verallgemeinerter Form kann letztlich jedes Zeichen als Trennzeichen genutzt werden; im deutschsprachigen Raum wird in <code>.csv</code>-Dateien häufig ein Semikolon <code>;</code> statt einem Komma genutzt <code>,</code> (z. B. wenn Sie Daten aus SPSS oder Excel als <code>.csv</code> exportieren):</p>
<pre><code>name;height;mass
Anakin Skywalker;188;84
Leia Organa;150;49
Luke Skywalker;172;77
Obi-Wan Kenobi;182;77</code></pre>
<p>Zwar kann R mittels unterschiedlicher Packages inzwischen auch relativ komfortabel Excel- und SPSS-Dateien einlesen; aus oben genannten Gründen werden wir zum Laden und Speichern jedoch vorrangig <code>.csv</code>-Dateien nutzen.</p>
</div>
</div>
<div id="willkommen-im-tidyverse" class="section level2">
<h2><span class="header-section-number">7.2</span> Willkommen im Tidyverse</h2>
<p>Die Idee, Datenhandling komplett codebasiert durchzuführen, erscheint zunächst vielleicht wenig komfortabel – vor allem wenn wir daran denken, dass das Auswählen und Verarbeiten von Dataframes bisher wenig intuitiv ablief (oder wissen Sie auf Anhieb noch, was der Unterschied zwischen <code>iris[, "Sepal.Width"]</code>, <code>iris$Sepal.Width</code> und <code>iris[["Sepal.Width"]]</code> ist?).<a href="#fn10" class="footnote-ref" id="fnref10"><sup>10</sup></a></p>
<p>Seit einigen Jahren hat sich jedoch das <a href="https://www.tidyverse.org/">Tidyverse</a> als Standard des Datenhandlings in R durchgesetzt, was die mit dem Datenhandling verbundenen Schritte deutlich vereinfacht. Dabei handelt es sich um ein sogenanntes Meta-Package, also eine Sammlung von verschiedenen Packages, die allesamt den gleichen Designprinzipien folgen, um Datenhandling zu vereinfachen und den zugehörigen Code möglichst lesbar (für Menschen) zu machen. So haben beispielsweise Funktionen im Tidyverse in der Regel Verben als Namen, die genau das beschreiben, was die Funktion macht.</p>
<blockquote>
<p>The tidyverse is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures.</p>
</blockquote>
<p>Das Tidyverse umfasst hierzu unter anderem Pakete für:</p>
<ul>
<li>Datenstrukturen (<code>tibble</code>)</li>
<li>Einlesen von Daten (z. B. <code>readr</code> für CSV, <code>haven</code> für SPSS, Stata und SAS, <code>readxl</code> für Excel)</li>
<li>Datentransformation und -modifikation (<code>tidyr</code>, <code>dplyr</code>)</li>
<li>Spezielle Objekttypen (z. B. <code>stringr</code> für die Arbeit mit Textobjekten, <code>forcats</code> für Faktoren, <code>lubridate</code> für Zeitdaten)</li>
<li>Programmieren mit R (<code>purrr</code>)</li>
<li>Grafik-/Diagrammerstellung (<code>ggplot2</code>)</li>
</ul>
<p>Alle Pakete lassen sich gesammelt installieren und laden<a href="#fn11" class="footnote-ref" id="fnref11"><sup>11</sup></a>:</p>
<div class="sourceCode" id="cb214"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb214-1" title="1"><span class="kw">install.packages</span>(<span class="st">&quot;tidyverse&quot;</span>) <span class="co"># Dies muss natürlich nur einmal ausgeführt werden</span></a>
<a class="sourceLine" id="cb214-2" title="2"><span class="kw">library</span>(tidyverse)</a></code></pre></div>
<p>Die Standard-Datenstruktur des Tidyverse ist das Tibble, das wir bereits aus Kapitel <a href="packages.html#usepackages">5.2</a> kennen. Zur Erinnerung, dabei handelt es sich im Wesentlichen um Dataframes mit einigen technischen und kosmetischen Verbesserungen:</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb215-1" title="1"><span class="kw">as_tibble</span>(iris)</a></code></pre></div>
<pre><code>## # A tibble: 150 x 5
##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
##           &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;  
##  1          5.1         3.5          1.4         0.2 setosa 
##  2          4.9         3            1.4         0.2 setosa 
##  3          4.7         3.2          1.3         0.2 setosa 
##  4          4.6         3.1          1.5         0.2 setosa 
##  5          5           3.6          1.4         0.2 setosa 
##  6          5.4         3.9          1.7         0.4 setosa 
##  7          4.6         3.4          1.4         0.3 setosa 
##  8          5           3.4          1.5         0.2 setosa 
##  9          4.4         2.9          1.4         0.2 setosa 
## 10          4.9         3.1          1.5         0.1 setosa 
## # ... with 140 more rows</code></pre>
<p>Im folgenden Kapitel werden wir uns nun ansehen, wie wir mittels Tidyverse-Funktionen Datensätze laden und modifizieren können.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="10">
<li id="fn10"><p>Die erste Variante resultiert in einem Dataframe, der lediglich <code>Sepal.Width</code> enthält, Varianten zwei und drei extrahieren diese Spalte als Vektor.<a href="einführung-in-das-datenhandling.html#fnref10" class="footnote-back">↩</a></p></li>
<li id="fn11"><p><code>library(tidyverse)</code> lädt dabei genauer gesagt die Kernpakete des Tidyverse, die die alltäglich am häufigsten genutzten Funktionen bereitstellen. Tidyverse-Packages für eher spezifische Anwendungsgebiete – z. B. <code>lubridate</code> für Zeitdaten oder <code>haven</code> für SPSS-Datensätze – müssen einzeln über den <code>library()</code>-Befehl geladen werden.<a href="einführung-in-das-datenhandling.html#fnref11" class="footnote-back">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="workflow.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="workingwithdata.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["ComputationalMethods.pdf", "ComputationalMethods.epub"],
"toc": {
"collapse": "section",
"depth": 3
},
"split_by": "chapter+number"
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
